name: data-pipeline-workflow

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome WebDriver
        run: |
          CHROME_DRIVER_VERSION=131.0.6778.204  # Replace with your desired version
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -N https://storage.googleapis.com/chrome-for-testing-public/$CHROME_DRIVER_VERSION/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver-linux64/chromedriver

      - name: Run States Data Script
        run: |
          python "data extraction/States_data.py"


      - name: Commit generated CSV files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add States_data.csv 
          git commit -m "Update States_data.csv"
          git push
