name: data-pipeline-workflow

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run States Data Script
        run: |
          python data extraction/States_data.py

      - name: Run VP Data Script
        run: |
          python data extraction/VP_data.py

      - name: Commit generated CSV files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add states_data.csv vp_data.csv
          git commit -m "Update states_data.csv and vp_data.csv"
          git push
